### ISSUE TITLE
I2C grove port not working with `Wire.h`

### ISSUE THREAD

**Issue by joernweissenborn** [infinimesh/sensorterminal-quickstart#1]
The I2C grove breakout port cannot be used with the libary `Wire.h`. 

I tried some alternatives without success.

A solution workaround is necessary, since many sensors rely on this bus.

**Comment by deBaer** [comment]
Hi, I just tried connecting a BME680 to the left Grove port and communicating with it using the BME680 library, which in turn uses Wire, and that works. See last commit.

**Comment by joernweissenborn** [comment]
I also tried different other sensors, both on the break out as well on the Grove. so it was an issue of the particular sensor, therfor closing.
